name: Deploy to Staging
on:
  push:
    branches:
      - main
jobs:
  redeploy_everything:
    name: Redeploying everything from main
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.STAGING_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - run: |
          ssh-keyscan -H 3.110.154.98 >> ~/.ssh/known_hosts

      - run: |
          ssh -i ~/.ssh/id_rsa root@3.110.154.98
          cd bms
          git pull
          pnpm install
          pnpm build
          pm2 restart fe-server
          pm2 restart http-server
          pm2 restart ws-server
